### ISSUE TITLE
Разрабы паровозики

### ISSUE THREAD

**Issue by 1Gregory** [ubots-tg/calc_ubot#3]
comb.comb_c(4,5)

**Comment by 1Gregory** [comment]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/gregory/PycharmProjects/calc_ubot/expeval/expeval.py", line 95, in __call__
    return executor()
  File "/home/gregory/PycharmProjects/calc_ubot/expeval/executor.py", line 147, in __call__
    self.brackets(0, "(", 0)
  File "/home/gregory/PycharmProjects/calc_ubot/expeval/executor.py", line 86, in brackets
    self.brackets(p, tk.token, 1 if called_by_func or called_by_operator else 0)
  File "/home/gregory/PycharmProjects/calc_ubot/expeval/executor.py", line 47, in brackets
    elem = self.brackets(p, bracket, 2)
  File "/home/gregory/PycharmProjects/calc_ubot/expeval/executor.py", line 68, in brackets
    raise Exception("Are you stupid? Wtf a separator doing here (%d)" % tk.st)
Exception: Are you stupid? Wtf a separator doing here (13)
